[workspace]
resolver = "3"
members = [ "dispencer", "kzg", "pod", "common", "storage-provider", "tests", "merkle_tree", "challenger"]

[workspace.dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "ansi"] }
tracing-appender = "0.2"
