[package]
name = "merkle_tree"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
hex = "0.4.3"
sha3 = "0.10.8"
eth_merkle_tree = "0.1.1"
common = { path = "../common" }
serde = "1.0.219"
itertools = "0.14.0"

[dev-dependencies]
rand = "0.9.1"
